"use client"

import Head from 'next/head'
import Image from 'next/image'

import { ThemeProvider } from 'next-themes'
import { useTheme } from 'next-themes'


import Navbar from './components/Navbar'
import Footer from './components/Footer'
import About from './components/About'

import useDarkMode from "./hooks/useDarkMode";
// import DarkModeToggle from './components/DarkModeToggle'



export default function Home() {
  const { theme, setTheme } = useTheme('light')
  return (
    <>
      <Head>
        <title>Philjgray.ca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider attribute='className'>
        <Navbar theme={theme} setTheme={setTheme} />

        <button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>toggle</button>

        <main className="flex  flex-col items-center justify-between p-24 bg-white-700">
          <About theme={theme} />
        </main>
        <Footer />
      </ThemeProvider>
    </>
  )
}
